module.exports = {
  apps: [
    {
      name: 'tradingview-bot-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: 'logs/web-error.log',
      out_file: 'logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
    },
    // 如果需要独立运行 Bot 服务（可选）
    // {
    //   name: 'tradingview-bot-cn',
    //   script: 'dist/bot-cn/index.js',
    //   cwd: './',
    //   instances: 1,
    //   exec_mode: 'fork',
    //   env: {
    //     NODE_ENV: 'production',
    //   },
    //   error_file: 'logs/bot-cn-error.log',
    //   out_file: 'logs/bot-cn-out.log',
    //   log_date_format: 'YYYY-MM-DD HH:mm:ss',
    //   merge_logs: true,
    //   autorestart: true,
    //   watch: false,
    //   max_memory_restart: '512M',
    //   min_uptime: '10s',
    //   max_restarts: 10,
    // },
    // {
    //   name: 'tradingview-bot-crypto',
    //   script: 'dist/bot-crypto/index.js',
    //   cwd: './',
    //   instances: 1,
    //   exec_mode: 'fork',
    //   env: {
    //     NODE_ENV: 'production',
    //   },
    //   error_file: 'logs/bot-crypto-error.log',
    //   out_file: 'logs/bot-crypto-out.log',
    //   log_date_format: 'YYYY-MM-DD HH:mm:ss',
    //   merge_logs: true,
    //   autorestart: true,
    //   watch: false,
    //   max_memory_restart: '512M',
    //   min_uptime: '10s',
    //   max_restarts: 10,
    // },
  ],
};
